this["JST"] = this["JST"] || {};

this["JST"]["src/js/templates/home.html"] = function(obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape;
with (obj) {
__p += '<div id="above-the-fold">\n    <section id="spotlight">\n        <div></div>\n        <h1><span>Experience Renaissance Movement Music</span></h1>\n        <p id="calls-to-action">\n            <a id="home-events">\n                <span></span>\n                <strong>Upcoming Events</strong>\n            </a>\n            <a id="home-book">\n                <span></span>\n                <strong>Book Now</strong>\n            </a>\n        </p>\n        <a id="home-play"></a>\n        <p id="open-rmtv"><a>Open <span>RMTV</span></a></p>\n    </section>\n    <a id="home-news">\n        <span></span>\n        <strong>News</strong>\n    </a>\n</div>\n<div id="below-the-fold">\n    <section id="news-teaser">\n        <div class="tiled-group">\n            <article>\n                <img src="/img/tile-example.jpg" alt="article title">\n                <h3>TITLE</h3>\n                <p>\n                    Author | Date<br>\n                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat <a href="">Read More</a>\n                </p>\n            </article>\n            <article>\n                <img src="/img/tile-example.jpg" alt="article title">\n                <h3>TITLE</h3>\n                <p>\n                    Author | Date<br>\n                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat <a href="">Read More</a>\n                </p>\n            </article>\n            <article>\n                <img src="/img/tile-example.jpg" alt="article title">\n                <h3>TITLE</h3>\n                <p>\n                    Author | Date<br>\n                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat <a href="">Read More</a>\n                </p>\n            </article>\n        </div>\n    </section>\n</div>';

}
return __p
};